//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Papeleria2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clientes()
        {
            this.Ordenes = new HashSet<Ordenes>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string email { get; set; }
        public string contrasenia { get; set; }
        public string cp { get; set; }
        public string entidad_federativa { get; set; }
        public string ciudad { get; set; }
        public string colonia { get; set; }
        public string direccion { get; set; }
        public string num_tarjeta { get; set; }
        public string mes_expiracion { get; set; }
        public string anio_expiracion { get; set; }
        public string cvv { get; set; }
        public string tipo_tarjeta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ordenes> Ordenes { get; set; }
    }
}
