//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Papeleria2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Empleados
    {
        public int id { get; set; }
        [Display(Name = "Nombre completo")]
        [Required(ErrorMessage = "Falta nombre")]
        public string nombre { get; set; }
        [Display(Name = "Email")]
        [Required(ErrorMessage = "Falta Email")]
        public string email { get; set; }
        [Display(Name = "Departamento")]
        [Required(ErrorMessage = "Falta depto")]
        public string departamento { get; set; }
        [Display(Name = "Constraseña")]
        [Required(ErrorMessage = "Falta contraseña")]
        public string contrasenia { get; set; }
    }
}
