//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Papeleria2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordenes
    {
        public int id { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public decimal total { get; set; }
        public string num_guia { get; set; }
        public Nullable<System.DateTime> fecha_entrega { get; set; }
        public Nullable<System.DateTime> fecha_envio { get; set; }
        public int id_cliente { get; set; }
        public string dir_entrega { get; set; }
        public Nullable<int> id_paqueteria { get; set; }
        public string status { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Paqueterias Paqueterias { get; set; }
    }
}
