//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Papeleria2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Orden_productos
    {
        [Display(Name = "Cantidad")]
        [Required(ErrorMessage = "Falta cantidad")]
        public int cantidad { get; set; }
        [Display(Name = "Producto")]
        [Required(ErrorMessage = "Falta producto")]
        public int id_producto { get; set; }
        [Display(Name = "Orden")]
        [Required(ErrorMessage = "Falta orden")]
        public int id_orden { get; set; }
    
        public virtual Productos Productos { get; set; }
    }
}
