//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Papeleria2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paqueterias
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string rfc { get; set; }
        public string tel { get; set; }
        public string web { get; set; }
        public string email { get; set; }
        public string direccion { get; set; }
        public string contacto { get; set; }
        public string telContacto { get; set; }
    }
}
