//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Papeleria2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Paqueterias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paqueterias()
        {
            this.Ordenes = new HashSet<Ordenes>();
        }
    
        public int id { get; set; }
        [Display(Name = "Nombre")]
        [Required(ErrorMessage = "Falta nombre")]
        public string nombre { get; set; }
        [Display(Name = "RFC")]
        [Required(ErrorMessage = "Falta RFC")]
        public string rfc { get; set; }
        [Display(Name = "Télefono")]
        [Required(ErrorMessage = "Falta telefono")]
        public string tel { get; set; }
        [Display(Name = "Sitio Web")]
        [Required(ErrorMessage = "Falta Sitio Web")]
        public string web { get; set; }
        [Display(Name = "Email")]
        [Required(ErrorMessage = "Falta Email")]
        public string email { get; set; }
        [Display(Name = "Dirección")]
        [Required(ErrorMessage = "Falta dirección")]
        public string direccion { get; set; }
        [Display(Name = "Nombre de Contacto")]
        [Required(ErrorMessage = "Falta nombre de contacto")]
        public string contacto { get; set; }
        [Display(Name = "Teléfono de Contacto")]
        [Required(ErrorMessage = "Falta teléfono de contacto")]
        public string telContacto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ordenes> Ordenes { get; set; }
    }
}
