//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Papeleria2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.Orden_productos = new HashSet<Orden_productos>();
        }
    
        public int id { get; set; }
        [Display(Name = "Nombre")]
        [Required(ErrorMessage = "Falta nombre")]
        public string nombre { get; set; }
        [Display(Name = "Descripción")]
        [Required(ErrorMessage = "Falta descipción")]
        public string descripcion { get; set; }
        [Display(Name = "Precio")]
        [Required(ErrorMessage = "Falta precio")]
        public decimal precio { get; set; }
        public Nullable<System.DateTime> ult_actualizacion { get; set; }
        [Display(Name = "Imagen")]
        [Required(ErrorMessage = "Falta imagen")]
        public string imagen { get; set; }
        [Display(Name = "No.Existencia")]
        [Required(ErrorMessage = "Falta no.existencia")]
        public Nullable<int> existencia { get; set; }
        [Display(Name = "Stock")]
        [Required(ErrorMessage = "Falta stock")]
        public Nullable<int> stock { get; set; }
        [Display(Name = "Categoria")]
        [Required(ErrorMessage = "Falta categoria")]
        public Nullable<int> id_categoria { get; set; }
    
        public virtual Categorias Categorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orden_productos> Orden_productos { get; set; }
    }
}
